### ISSUE TITLE
您好，想咨询一下有关测试代码SR的问题

### ISSUE THREAD

**Issue by LTTdouble** [qianngli/DualSR#2]
您好，读了您的DualSR代码，角度很新颖，很感谢您能提供新思路和改代码供我们读者借鉴。我对test.py中的SR有点疑惑，代码中SR=np.array(HR).astype(np.float32)，这句如果这样设计，SR是否读取了HR中的值，后续的PSNR(SR,HR)等指标的计算会不会受到影响？比如模型的输出在CAVE 4X情况下是512*512，那SR是31*512*512，那SR中的31个光谱波段是HR中的吗。
        我的理解可能会存在误解，希望您能指点迷津，再次感谢您提供的新思路和代码！

**Comment by qianngli** [comment]
1. SR的值不会影响，这里只是创建一个与HR一样大小的array，在62行，会有SR的重新赋值。
2. 这里是对每个波段（512x512）进行超分辨，通过循环的方式获得所有的波段(代码74-117行)，完成整幅图像超分辨，获得粗结果。

LTTdouble ***@***.***> 于2023年7月21日周五 11:38写道：

**Comment by LTTdouble** [comment]
很感谢您的回复，明白了。我尝试把SR=np.array(HR).astype(np.float32)这句屏蔽了，不对SR重新赋值；由于光谱维度的for循环中SR是不断迭代的，for循环结束后把模型最后输出的SR修改为31*512*512，然后和HR做指标计算，最终的指标值不是很好。我继续探索原因，再次感谢提供的代码和思路。
